name:                discord-unknown-spells
version:             0.1.0.0
github:              "githubuser/discord-unknown-spells"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/discord-unknown-spells#readme>

dependencies:
- base >= 4.7 && < 5
- discord-haskell
- text
- mtl
- transformers
- safe
- aeson
- bytestring
- cryptonite
- unliftio
- memory
- time
- containers
- double-conversion
- either
- directory

library:
  source-dirs: src

executables:
  discord-unknown-spells-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-unknown-spells

tests:
  discord-unknown-spells-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-unknown-spells
